### ISSUE TITLE
False

### ISSUE THREAD

**Issue by FelixDYS** [SecondReality/VirtualControllerDriver#1]
Yesterday was successful, but today again, the third controller does not appear, I did not change anything

**Comment by SecondReality** [comment]
@felixxxp Could you start SteamVR, then attach your vrserver.txt log file? (usually in Program Files (x86)/Steam/Logs. This should help me diagnose what is going on.

**Comment by CoOpSisters** [comment]
Hi hope you can help, im having the same prob. it syoped working last night for no reason, can't get it to work no mater what i do, can you help please.

Thu Jul 07 2016 06:39:49.366 - 
Unable to load driver virtualcontroller from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\virtualcontroller\bin\win64\driver_virtualcontroller.dll.
Thu Jul 07 2016 06:39:49.366 - 
error VRInitError_Init_HmdNotFound when initing driver null from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\null\bin\win64\driver_null.dll.
Thu Jul 07 2016 06:39:49.366 -
Active HMD set to lighthouse.LHR-27220BD7

**Comment by mpisco** [comment]
Also unable to get the third controller recognized.  I noticed during the first attempt Steam automatically emptied the virtualcontroller folder.  I have the same error as CoOpSisters.

**Comment by invincie** [comment]
I have the exact same error but noticed the following:
SteamVR seems to be looking in ..\win64 directory whereas driver_virtualcontroller.dll is located in a ..\win32 directory. Tried copying it in such a directory but no luck.

**Comment by SecondReality** [comment]
Thanks for the reports.
I believe steam is starting to use 64 bit by default, and the current DLL is 32 bit.
I'll make new builds when I'm home (I'm out till Tuesday).

**Comment by mpisco** [comment]
Awesome! Can't wait thank you SecondReality!

**Comment by SecondReality** [comment]
Hello all,
New drivers are available, which includes 64bit versions: **[download the new driver here.](http://secondreality.co.uk/MixedRealityTwoController-0-0-3.zip)**

I'm going to update the [article on my blog](http://secondreality.co.uk/blog/how-to-create-mixed-reality-videos-for-the-vive-with-two-controllers/).

_I reopened this issue ...I accidentally closed it before._
Let me know if you have any problems.

**Comment by mpisco** [comment]
You're my hero man.  Thanks so much!  Worked like a charm for me!

**Comment by CoOpSisters** [comment]
OMG! we <3 you, do you have a donation page?

**Comment by SecondReality** [comment]
@CoOpSisters 

I added a link to donate to childs play at the bottom of the [page on my blog](http://secondreality.co.uk/blog/how-to-create-mixed-reality-videos-for-the-vive-with-two-controllers/).
Any donations would make me happy, cheers!

**Comment by CoOpSisters** [comment]
Awesome!!! your amazing for what u have done for us :)

**Comment by CoOpSisters** [comment]
Donation made :)
Thank you again!

**Comment by FelixDYS** [comment]
@SecondReality ,sir，Thank you for your reply, your Tool is useful for me.  I have a question，if I have 3 controllers, Can I use it to get the externalcamera.cfg for MR?

**Comment by SecondReality** [comment]
@felixxxp If you download the zip file from [the blog post](http://secondreality.co.uk/blog/how-to-create-mixed-reality-videos-for-the-vive-with-two-controllers/) it will contain a config file. There's also a program in there to help you set the values in it.

Jessie made a [video](https://www.youtube.com/watch?v=jNHS3JUp2D0&feature=youtu.be) showing how to set everything up.
