### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by jkafkaris** [SecondReality/VirtualControllerDriver#4]
Hi, I went to your site - http://secondreality.co.uk/blog/how-to-create-mixed-reality-videos-for-the-vive-with-two-controllers/ - for instructions but it appears to be down.

Can you please advise what the instructions are (or get the site back up!)?

Thanks.

**Comment by SecondReality** [comment]
Thanks jkafkaris, my host migrated the servers - I think I simply need to restart some services. I'll update you when it is up.

**Comment by SecondReality** [comment]
The website is now up @jkafkaris, thanks again.

**Comment by SecondReality** [comment]
It's down again - will fix later today.
